/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AccessTokenPutRequest : 请求更新访问令牌的模型
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessTokenPutRequest {
    /// 访问令牌的标题
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    /// 访问令牌的标签
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    /// 访问令牌的描述
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// 访问令牌的权限
    #[serde(rename = "permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Option<String>>,
    /// 是否启用访问令牌
    #[serde(rename = "enable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable: Option<Option<bool>>,
}

impl AccessTokenPutRequest {
    /// 请求更新访问令牌的模型
    pub fn new() -> AccessTokenPutRequest {
        AccessTokenPutRequest {
            title: None,
            tags: None,
            description: None,
            permissions: None,
            enable: None,
        }
    }
}

