/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AlipayCreateOrderWapPayRequest {
    /// 自定义订单号
    #[serde(rename = "orderNo")]
    pub order_no: String,
    /// 订单金额。例如：0.01
    #[serde(rename = "amount")]
    pub amount: f64,
    /// 商品名称
    #[serde(rename = "subject")]
    pub subject: String,
    /// 支付完成后返回的URL地址
    #[serde(rename = "returnUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub return_url: Option<Option<String>>,
}

impl AlipayCreateOrderWapPayRequest {
    pub fn new(order_no: String, amount: f64, subject: String) -> AlipayCreateOrderWapPayRequest {
        AlipayCreateOrderWapPayRequest {
            order_no,
            amount,
            subject,
            return_url: None,
        }
    }
}

