/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppUserResetPwdRequest {
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "pwd")]
    pub pwd: String,
}

impl AppUserResetPwdRequest {
    pub fn new(code: String, pwd: String) -> AppUserResetPwdRequest {
        AppUserResetPwdRequest {
            phone: None,
            email: None,
            code,
            pwd,
        }
    }
}

