/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppUserResetPhoneRequest {
    /// 手机号码
    #[serde(rename = "phone", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub phone: Option<Option<String>>,
    /// 手机验证码
    #[serde(rename = "code")]
    pub code: String,
}

impl AppUserResetPhoneRequest {
    pub fn new(code: String) -> AppUserResetPhoneRequest {
        AppUserResetPhoneRequest {
            phone: None,
            code,
        }
    }
}

