/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppSetting : 应用设置
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppSetting {
    /// 唯一标识
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 提供商代码
    #[serde(rename = "providerCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub provider_code: Option<Option<String>>,
    /// 分组代码
    #[serde(rename = "groupCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group_code: Option<Option<String>>,
    /// 设置项代码
    #[serde(rename = "code")]
    pub code: String,
    /// 设置值
    #[serde(rename = "value")]
    pub value: String,
    /// 标签
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    /// 描述
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// 是否在前端可用
    #[serde(rename = "frontendUsable", skip_serializing_if = "Option::is_none")]
    pub frontend_usable: Option<bool>,
    /// 创建时间
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// 最后更新时间
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
}

impl AppSetting {
    /// 应用设置
    pub fn new(code: String, value: String) -> AppSetting {
        AppSetting {
            id: None,
            provider_code: None,
            group_code: None,
            code,
            value,
            tags: None,
            description: None,
            frontend_usable: None,
            create_date: None,
            last_update: None,
        }
    }
}

