/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContributeDetail {
    #[serde(rename = "contributeAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contribute_amount: Option<Option<String>>,
    #[serde(rename = "contributeType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contribute_type: Option<Option<String>>,
}

impl ContributeDetail {
    pub fn new() -> ContributeDetail {
        ContributeDetail {
            contribute_amount: None,
            contribute_type: None,
        }
    }
}

