/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Currency : 货币实体，用于表示和管理不同类型的货币信息。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Currency {
    /// 货币的唯一标识符。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 货币的名称，例如 '人民币', '美元' 等。
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// 货币的ISO标准代码，例如 'CNY', 'USD' 等。
    #[serde(rename = "code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code: Option<Option<String>>,
    /// 货币的符号，例如 '$', '€', '¥' 等。
    #[serde(rename = "symbol", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<Option<String>>,
    /// 发行该货币的机构或国家名称。
    #[serde(rename = "issuer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub issuer: Option<Option<String>>,
    /// 货币的类型，例如 '法定货币', '加密货币' 等。
    #[serde(rename = "currencyType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_type: Option<Option<String>>,
    /// 用于分类或标记货币的标签。
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    /// 指示货币当前是否可用。
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<bool>,
    /// 指示该货币是否允许进行虚拟充值。
    #[serde(rename = "enableVirtualRecharge", skip_serializing_if = "Option::is_none")]
    pub enable_virtual_recharge: Option<bool>,
    /// 指示该货币是否允许进行虚拟消费。
    #[serde(rename = "enableVirtualConsume", skip_serializing_if = "Option::is_none")]
    pub enable_virtual_consume: Option<bool>,
    /// 货币的详细描述信息。
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// 该货币与法定货币的兑换比率。
    #[serde(rename = "fiatExchangeRate", skip_serializing_if = "Option::is_none")]
    pub fiat_exchange_rate: Option<i64>,
    /// 每日通过法定货币充值的最大限额。
    #[serde(rename = "fiatDailyRechargeLimit", skip_serializing_if = "Option::is_none")]
    pub fiat_daily_recharge_limit: Option<i64>,
    /// 货币的总供应量，0 表示无限制。
    #[serde(rename = "totalSupply", skip_serializing_if = "Option::is_none")]
    pub total_supply: Option<i64>,
    /// 货币记录的创建日期，默认为当前时间。
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// 货币记录的最后更新日期，默认为当前时间。
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
}

impl Currency {
    /// 货币实体，用于表示和管理不同类型的货币信息。
    pub fn new() -> Currency {
        Currency {
            id: None,
            name: None,
            code: None,
            symbol: None,
            issuer: None,
            currency_type: None,
            tags: None,
            status: None,
            enable_virtual_recharge: None,
            enable_virtual_consume: None,
            description: None,
            fiat_exchange_rate: None,
            fiat_daily_recharge_limit: None,
            total_supply: None,
            create_date: None,
            last_update: None,
        }
    }
}

