/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeRatePutRequest {
    #[serde(rename = "toCurrencyCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub to_currency_code: Option<Option<String>>,
    #[serde(rename = "exchangeRate", skip_serializing_if = "Option::is_none")]
    pub exchange_rate: Option<i64>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl ExchangeRatePutRequest {
    pub fn new() -> ExchangeRatePutRequest {
        ExchangeRatePutRequest {
            to_currency_code: None,
            exchange_rate: None,
            description: None,
        }
    }
}

