/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeCurrencyRequest {
    /// 源虚拟币代码
    #[serde(rename = "fromCurrency")]
    pub from_currency: String,
    /// 目标虚拟币代码
    #[serde(rename = "currency")]
    pub currency: String,
    /// 兑换额
    #[serde(rename = "balance")]
    pub balance: i32,
    /// 备注
    #[serde(rename = "remark", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remark: Option<Option<String>>,
    /// 描述
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// 标签
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
}

impl ExchangeCurrencyRequest {
    pub fn new(from_currency: String, currency: String, balance: i32) -> ExchangeCurrencyRequest {
        ExchangeCurrencyRequest {
            from_currency,
            currency,
            balance,
            remark: None,
            description: None,
            tags: None,
        }
    }
}

