/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecuteFunctionRequest {
    /// 函数标识
    #[serde(rename = "functionKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub function_key: Option<Option<String>>,
}

impl ExecuteFunctionRequest {
    pub fn new() -> ExecuteFunctionRequest {
        ExecuteFunctionRequest {
            function_key: None,
        }
    }
}

