/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalAccountBindRequest {
    #[serde(rename = "unionID")]
    pub union_id: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "platformName")]
    pub platform_name: String,
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
}

impl ExternalAccountBindRequest {
    pub fn new(union_id: String, platform: String, platform_name: String) -> ExternalAccountBindRequest {
        ExternalAccountBindRequest {
            union_id,
            platform,
            platform_name,
            avatar: None,
            data: None,
        }
    }
}

