/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalAccountSignInRequest {
    /// UnionID，长度必须在1到50个字符之间，只能包含字母、数字、下划线和连字符
    #[serde(rename = "unionID")]
    pub union_id: String,
    /// 平台，长度必须在1到20个字符之间，只能包含字母和数字
    #[serde(rename = "platform")]
    pub platform: String,
    /// 双因素认证代码，如果启用双因素认证登录，则必填，长度必须为6个字符，只能包含数字
    #[serde(rename = "twoFactorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub two_factor_code: Option<Option<String>>,
}

impl ExternalAccountSignInRequest {
    pub fn new(union_id: String, platform: String) -> ExternalAccountSignInRequest {
        ExternalAccountSignInRequest {
            union_id,
            platform,
            two_factor_code: None,
        }
    }
}

