/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FollowerModel {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "targetUserID", skip_serializing_if = "Option::is_none")]
    pub target_user_id: Option<i64>,
    #[serde(rename = "alias", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alias: Option<Option<String>>,
    #[serde(rename = "nickName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nick_name: Option<Option<String>>,
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    #[serde(rename = "isMutual", skip_serializing_if = "Option::is_none")]
    pub is_mutual: Option<bool>,
    #[serde(rename = "closenessScore", skip_serializing_if = "Option::is_none")]
    pub closeness_score: Option<i64>,
    #[serde(rename = "attentionScore", skip_serializing_if = "Option::is_none")]
    pub attention_score: Option<i64>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    #[serde(rename = "remark", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remark: Option<Option<String>>,
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
}

impl FollowerModel {
    pub fn new() -> FollowerModel {
        FollowerModel {
            id: None,
            target_user_id: None,
            alias: None,
            nick_name: None,
            avatar: None,
            is_mutual: None,
            closeness_score: None,
            attention_score: None,
            tags: None,
            status: None,
            remark: None,
            create_date: None,
        }
    }
}

