/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FollowerPutModel {
    /// 别名
    #[serde(rename = "alias", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alias: Option<Option<String>>,
    /// 亲密度分数
    #[serde(rename = "closenessScore", skip_serializing_if = "Option::is_none")]
    pub closeness_score: Option<i64>,
    /// 关注度分数
    #[serde(rename = "attentionScore", skip_serializing_if = "Option::is_none")]
    pub attention_score: Option<i64>,
    /// 标签
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    /// 状态
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    /// 备注
    #[serde(rename = "remark", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remark: Option<Option<String>>,
}

impl FollowerPutModel {
    pub fn new() -> FollowerPutModel {
        FollowerPutModel {
            alias: None,
            closeness_score: None,
            attention_score: None,
            tags: None,
            status: None,
            remark: None,
        }
    }
}

