/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FulfillmentDetail {
    #[serde(rename = "fulfillmentAmount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fulfillment_amount: Option<Option<String>>,
    #[serde(rename = "gmtPayment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gmt_payment: Option<Option<String>>,
    #[serde(rename = "outRequestNo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub out_request_no: Option<Option<String>>,
}

impl FulfillmentDetail {
    pub fn new() -> FulfillmentDetail {
        FulfillmentDetail {
            fulfillment_amount: None,
            gmt_payment: None,
            out_request_no: None,
        }
    }
}

