/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GoodsDetail {
    #[serde(rename = "alipayGoodsId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alipay_goods_id: Option<Option<String>>,
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    #[serde(rename = "categoriesTree", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub categories_tree: Option<Option<String>>,
    #[serde(rename = "goodsCategory", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub goods_category: Option<Option<String>>,
    #[serde(rename = "goodsId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub goods_id: Option<Option<String>>,
    #[serde(rename = "goodsName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub goods_name: Option<Option<String>>,
    #[serde(rename = "outItemId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub out_item_id: Option<Option<String>>,
    #[serde(rename = "outSkuId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub out_sku_id: Option<Option<String>>,
    #[serde(rename = "price", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price: Option<Option<String>>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<i64>,
    #[serde(rename = "showUrl", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub show_url: Option<Option<String>>,
}

impl GoodsDetail {
    pub fn new() -> GoodsDetail {
        GoodsDetail {
            alipay_goods_id: None,
            body: None,
            categories_tree: None,
            goods_category: None,
            goods_id: None,
            goods_name: None,
            out_item_id: None,
            out_sku_id: None,
            price: None,
            quantity: None,
            show_url: None,
        }
    }
}

