/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Order : 订单实体，用于记录用户的订单信息。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Order {
    /// 订单的唯一标识符。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 创建订单的用户ID。
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    /// 订单的支付类型，例如 '信用卡', '支付宝', '微信支付' 等。
    #[serde(rename = "payType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pay_type: Option<Option<String>>,
    /// 订单的总金额。
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<f64>,
    /// 订单的唯一编号，通常由系统生成。
    #[serde(rename = "orderNo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub order_no: Option<Option<String>>,
    /// 与订单关联的交易编号，通常由支付平台提供。
    #[serde(rename = "tradeNo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trade_no: Option<Option<String>>,
    /// 订单的当前状态，例如 '待支付', '已完成', '已取消' 等。
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<String>>,
    /// 订单中商品的类型分类。
    #[serde(rename = "productType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_type: Option<Option<String>>,
    /// 订单中商品的唯一标识符。
    #[serde(rename = "productID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_id: Option<Option<String>>,
    /// 订单中商品的名称。
    #[serde(rename = "productName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub product_name: Option<Option<String>>,
    /// 指示订单是否允许进行退款操作。
    #[serde(rename = "allowRefund", skip_serializing_if = "Option::is_none")]
    pub allow_refund: Option<bool>,
    /// 订单允许进行退款操作的截止时间。
    #[serde(rename = "allowRefundUntil", skip_serializing_if = "Option::is_none")]
    pub allow_refund_until: Option<String>,
    /// 用于分类或标记订单的标签。
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    /// 订单的额外备注信息。
    #[serde(rename = "remark", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remark: Option<Option<String>>,
    /// 订单的详细描述信息。
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// 订单完成支付的时间。
    #[serde(rename = "orderPayTime", skip_serializing_if = "Option::is_none")]
    pub order_pay_time: Option<String>,
    /// 订单的过期时间，超过该时间订单将自动取消。
    #[serde(rename = "expireTime", skip_serializing_if = "Option::is_none")]
    pub expire_time: Option<String>,
    /// 订单的创建时间，默认为当前时间。
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// 订单的最后更新时间，默认为当前时间。
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
}

impl Order {
    /// 订单实体，用于记录用户的订单信息。
    pub fn new() -> Order {
        Order {
            id: None,
            user_id: None,
            pay_type: None,
            amount: None,
            order_no: None,
            trade_no: None,
            status: None,
            product_type: None,
            product_id: None,
            product_name: None,
            allow_refund: None,
            allow_refund_until: None,
            tags: None,
            remark: None,
            description: None,
            order_pay_time: None,
            expire_time: None,
            create_date: None,
            last_update: None,
        }
    }
}

