/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaymentInfoWithId {
    #[serde(rename = "paymentIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
}

impl PaymentInfoWithId {
    pub fn new() -> PaymentInfoWithId {
        PaymentInfoWithId {
            payment_ids: None,
            r#type: None,
        }
    }
}

