/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PhoneSignUpRequest {
    #[serde(rename = "phone")]
    pub phone: String,
    /// 手机验证码
    #[serde(rename = "phoneCode")]
    pub phone_code: String,
    #[serde(rename = "pwd")]
    pub pwd: String,
    /// 邮箱
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<String>>,
    /// 邮箱验证码（只有启用的邮箱验证码功能时，才需要传入）
    #[serde(rename = "emailCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email_code: Option<Option<String>>,
    /// 昵称
    #[serde(rename = "nickName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nick_name: Option<Option<String>>,
    /// 头像
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    /// 自定义数据
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
}

impl PhoneSignUpRequest {
    pub fn new(phone: String, phone_code: String, pwd: String) -> PhoneSignUpRequest {
        PhoneSignUpRequest {
            phone,
            phone_code,
            pwd,
            email: None,
            email_code: None,
            nick_name: None,
            avatar: None,
            data: None,
        }
    }
}

