/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PresetPayToolInfo {
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<Vec<String>>>,
    #[serde(rename = "assertTypeCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub assert_type_code: Option<Option<String>>,
}

impl PresetPayToolInfo {
    pub fn new() -> PresetPayToolInfo {
        PresetPayToolInfo {
            amount: None,
            assert_type_code: None,
        }
    }
}

