/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QrCodeSignInRequest {
    /// 登录密钥
    #[serde(rename = "signInKey")]
    pub sign_in_key: i64,
}

impl QrCodeSignInRequest {
    pub fn new(sign_in_key: i64) -> QrCodeSignInRequest {
        QrCodeSignInRequest {
            sign_in_key,
        }
    }
}

