/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QrCodePreSignInRequest {
    /// 授权范围，长度不能超过100个字符，只能包含字母、数字和逗号
    #[serde(rename = "scopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Option<String>>,
    /// 备注，长度不能超过200个字符
    #[serde(rename = "remark", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remark: Option<Option<String>>,
    /// 方案，长度不能超过50个字符，只能包含字母和数字
    #[serde(rename = "scheme", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scheme: Option<Option<String>>,
}

impl QrCodePreSignInRequest {
    pub fn new() -> QrCodePreSignInRequest {
        QrCodePreSignInRequest {
            scopes: None,
            remark: None,
            scheme: None,
        }
    }
}

