/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecommendFriend {
    /// 用户ID
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    /// 昵称
    #[serde(rename = "nickName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nick_name: Option<Option<String>>,
    /// 头像
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    /// 性别
    #[serde(rename = "gender", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gender: Option<Option<String>>,
    /// 年龄
    #[serde(rename = "age", skip_serializing_if = "Option::is_none")]
    pub age: Option<i32>,
    /// 兴趣标签
    #[serde(rename = "interestTags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interest_tags: Option<Option<String>>,
    /// 位置名称
    #[serde(rename = "locationName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_name: Option<Option<String>>,
    /// 纬度
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// 经度
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    /// 距离
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<i64>,
    /// 个人简介
    #[serde(rename = "biography", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub biography: Option<Option<String>>,
    /// 国家
    #[serde(rename = "country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country: Option<Option<String>>,
    /// 省份
    #[serde(rename = "state", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state: Option<Option<String>>,
    /// 城市
    #[serde(rename = "city", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city: Option<Option<String>>,
    /// 区县
    #[serde(rename = "district", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub district: Option<Option<String>>,
}

impl RecommendFriend {
    pub fn new() -> RecommendFriend {
        RecommendFriend {
            user_id: None,
            nick_name: None,
            avatar: None,
            gender: None,
            age: None,
            interest_tags: None,
            location_name: None,
            latitude: None,
            longitude: None,
            distance: None,
            biography: None,
            country: None,
            state: None,
            city: None,
            district: None,
        }
    }
}

