/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecommendFriend {
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    #[serde(rename = "nickName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nick_name: Option<Option<String>>,
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    #[serde(rename = "gender", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gender: Option<Option<String>>,
    #[serde(rename = "age", skip_serializing_if = "Option::is_none")]
    pub age: Option<i32>,
    #[serde(rename = "interestTags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interest_tags: Option<Option<String>>,
    #[serde(rename = "locationName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_name: Option<Option<String>>,
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    #[serde(rename = "distance", skip_serializing_if = "Option::is_none")]
    pub distance: Option<i64>,
}

impl RecommendFriend {
    pub fn new() -> RecommendFriend {
        RecommendFriend {
            user_id: None,
            nick_name: None,
            avatar: None,
            gender: None,
            age: None,
            interest_tags: None,
            location_name: None,
            latitude: None,
            longitude: None,
            distance: None,
        }
    }
}

