/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RefundSubFee {
    #[serde(rename = "refundChargeFee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub refund_charge_fee: Option<Option<String>>,
    #[serde(rename = "switchFeeRate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub switch_fee_rate: Option<Option<String>>,
}

impl RefundSubFee {
    pub fn new() -> RefundSubFee {
        RefundSubFee {
            refund_charge_fee: None,
            switch_fee_rate: None,
        }
    }
}

