/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReturnPageNotifyRequest : 支付宝返回页面通知请求
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReturnPageNotifyRequest {
    /// 应用ID
    #[serde(rename = "app_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<Option<String>>,
    /// 授权应用ID
    #[serde(rename = "auth_app_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auth_app_id: Option<Option<String>>,
    /// 字符集
    #[serde(rename = "charset", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub charset: Option<Option<String>>,
    /// 接口名称
    #[serde(rename = "method", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub method: Option<Option<String>>,
    /// 商户订单号
    #[serde(rename = "out_trade_no", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub out_trade_no: Option<Option<String>>,
    /// 卖家支付宝用户号
    #[serde(rename = "seller_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub seller_id: Option<Option<String>>,
    /// 签名
    #[serde(rename = "sign", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sign: Option<Option<String>>,
    /// 签名类型
    #[serde(rename = "sign_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sign_type: Option<Option<String>>,
    /// 时间戳
    #[serde(rename = "timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<Option<String>>,
    /// 订单总金额
    #[serde(rename = "total_amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_amount: Option<Option<String>>,
    /// 支付宝交易号
    #[serde(rename = "trade_no", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trade_no: Option<Option<String>>,
    /// 接口版本
    #[serde(rename = "version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub version: Option<Option<String>>,
}

impl ReturnPageNotifyRequest {
    /// 支付宝返回页面通知请求
    pub fn new() -> ReturnPageNotifyRequest {
        ReturnPageNotifyRequest {
            app_id: None,
            auth_app_id: None,
            charset: None,
            method: None,
            out_trade_no: None,
            seller_id: None,
            sign: None,
            sign_type: None,
            timestamp: None,
            total_amount: None,
            trade_no: None,
            version: None,
        }
    }
}

