/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendEmailCodeRequest {
    /// 用户邮箱地址
    #[serde(rename = "email")]
    pub email: String,
    /// 用途。可选值：signup（注册）/forgetpwd（忘记密码）
    #[serde(rename = "type")]
    pub r#type: String,
}

impl SendEmailCodeRequest {
    pub fn new(email: String, r#type: String) -> SendEmailCodeRequest {
        SendEmailCodeRequest {
            email,
            r#type,
        }
    }
}

