/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SendSmsCodeRequest {
    /// 用户手机号
    #[serde(rename = "phone")]
    pub phone: String,
    /// 用途。可选值：signup（注册）/forgetpwd（忘记密码）
    #[serde(rename = "type")]
    pub r#type: String,
}

impl SendSmsCodeRequest {
    pub fn new(phone: String, r#type: String) -> SendSmsCodeRequest {
        SendSmsCodeRequest {
            phone,
            r#type,
        }
    }
}

