/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServiceProvider : 服务商实体，用于表示和管理系统中的服务提供方信息。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceProvider {
    /// 服务商的唯一标识符。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 服务商的业务代码，用于标识其所属业务领域。
    #[serde(rename = "bizCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub biz_code: Option<Option<String>>,
    /// 服务商的名称。
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// 服务商的唯一代码，用于系统内部标识。
    #[serde(rename = "code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code: Option<Option<String>>,
    /// 服务商图标的URL或路径。
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    /// 服务商的详细描述信息。
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// 用于分类或标记服务商的标签。
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    /// 指示服务商是否在界面上显示。
    #[serde(rename = "show", skip_serializing_if = "Option::is_none")]
    pub show: Option<bool>,
    /// 服务商在界面上的显示顺序。
    #[serde(rename = "showIndex", skip_serializing_if = "Option::is_none")]
    pub show_index: Option<i32>,
    /// 服务商记录的创建日期，默认为当前时间。
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// 服务商记录的最后更新日期，默认为当前时间。
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
}

impl ServiceProvider {
    /// 服务商实体，用于表示和管理系统中的服务提供方信息。
    pub fn new() -> ServiceProvider {
        ServiceProvider {
            id: None,
            biz_code: None,
            name: None,
            code: None,
            icon: None,
            description: None,
            tags: None,
            show: None,
            show_index: None,
            create_date: None,
            last_update: None,
        }
    }
}

