/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignInRequest {
    /// 用户名，长度必须在6到32个字符之间，只能包含字母、数字、下划线和连字符
    #[serde(rename = "userName")]
    pub user_name: String,
    /// 用户密码，长度必须在6到50个字符之间，可以包含数字、大小写字母、下划线、连字符和特殊符号
    #[serde(rename = "pwd")]
    pub pwd: String,
    /// 双因素认证代码，如果启用双因素认证登录，则必填，长度必须为6个字符，只能包含数字
    #[serde(rename = "twoFactorCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub two_factor_code: Option<Option<String>>,
}

impl SignInRequest {
    pub fn new(user_name: String, pwd: String) -> SignInRequest {
        SignInRequest {
            user_name,
            pwd,
            two_factor_code: None,
        }
    }
}

