/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Team : 团队
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Team {
    /// ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 用户ID
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    /// 渠道代码
    #[serde(rename = "channelCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel_code: Option<Option<String>>,
    /// 渠道应用ID
    #[serde(rename = "channelAppID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel_app_id: Option<Option<String>>,
    /// 角色
    #[serde(rename = "role", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role: Option<Option<String>>,
    /// 权限
    #[serde(rename = "permission", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permission: Option<Option<String>>,
    /// 是否显示
    #[serde(rename = "show", skip_serializing_if = "Option::is_none")]
    pub show: Option<bool>,
    /// 显示顺序
    #[serde(rename = "showIndex", skip_serializing_if = "Option::is_none")]
    pub show_index: Option<i64>,
    /// 创建日期
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// 最后更新日期
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
}

impl Team {
    /// 团队
    pub fn new() -> Team {
        Team {
            id: None,
            user_id: None,
            channel_code: None,
            channel_app_id: None,
            role: None,
            permission: None,
            show: None,
            show_index: None,
            create_date: None,
            last_update: None,
        }
    }
}

