/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TradeSettleDetail {
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<String>>,
    #[serde(rename = "operationDt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub operation_dt: Option<Option<String>>,
    #[serde(rename = "operationSerialNo", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub operation_serial_no: Option<Option<String>>,
    #[serde(rename = "operationType", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub operation_type: Option<Option<String>>,
    #[serde(rename = "oriTransIn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ori_trans_in: Option<Option<String>>,
    #[serde(rename = "oriTransOut", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ori_trans_out: Option<Option<String>>,
    #[serde(rename = "transIn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trans_in: Option<Option<String>>,
    #[serde(rename = "transOut", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub trans_out: Option<Option<String>>,
}

impl TradeSettleDetail {
    pub fn new() -> TradeSettleDetail {
        TradeSettleDetail {
            amount: None,
            operation_dt: None,
            operation_serial_no: None,
            operation_type: None,
            ori_trans_in: None,
            ori_trans_out: None,
            trans_in: None,
            trans_out: None,
        }
    }
}

