/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserAccessToken : 用户令牌实体，用于管理用户的访问令牌及其相关信息。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAccessToken {
    /// 用户令牌的唯一标识符。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 与令牌关联的用户ID。
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    /// 指示令牌是否处于启用状态。
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    /// 令牌拥有的权限列表，多个权限以逗号分隔。
    #[serde(rename = "permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Option<String>>,
    /// 令牌的标题或名称，用于标识令牌。
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    /// 访问令牌的具体值，用于身份验证。
    #[serde(rename = "accessToken", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<Option<String>>,
    /// 用于分类或标记令牌的标签。
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    /// 令牌的详细描述信息。
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// 令牌的过期时间，超过该时间令牌将失效。
    #[serde(rename = "expireTime", skip_serializing_if = "Option::is_none")]
    pub expire_time: Option<String>,
    /// 令牌的创建日期，默认为当前时间。
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// 令牌的最后更新日期，默认为当前时间。
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
}

impl UserAccessToken {
    /// 用户令牌实体，用于管理用户的访问令牌及其相关信息。
    pub fn new() -> UserAccessToken {
        UserAccessToken {
            id: None,
            user_id: None,
            enable: None,
            permissions: None,
            title: None,
            access_token: None,
            tags: None,
            description: None,
            expire_time: None,
            create_date: None,
            last_update: None,
        }
    }
}

