/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserCurrency : 用户资产实体，用于记录用户的货币余额和相关信息。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCurrency {
    /// 用户资产的唯一标识符。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 与用户资产关联的用户ID。
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    /// 用户资产的货币代码，例如 'USD', 'CNY' 等。
    #[serde(rename = "currencyCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<Option<String>>,
    /// 用户的账户余额，表示当前持有的货币数量。
    #[serde(rename = "balance", skip_serializing_if = "Option::is_none")]
    pub balance: Option<i64>,
}

impl UserCurrency {
    /// 用户资产实体，用于记录用户的货币余额和相关信息。
    pub fn new() -> UserCurrency {
        UserCurrency {
            id: None,
            user_id: None,
            currency_code: None,
            balance: None,
        }
    }
}

