/*
 * 全部  API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserSetting : 用户配置实体，用于存储用户的个性化设置。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSetting {
    /// 用户的唯一标识符。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 关联的用户ID，表示该配置属于哪个用户。
    #[serde(rename = "userID")]
    pub user_id: i64,
    /// 提供商的唯一代码，用于标识服务提供者。
    #[serde(rename = "providerCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub provider_code: Option<Option<String>>,
    /// 组的唯一代码，用于分类设置项。
    #[serde(rename = "groupCode", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub group_code: Option<Option<String>>,
    /// 设置项的唯一代码或键名，用于标识具体的配置项。
    #[serde(rename = "code")]
    pub code: String,
    /// 设置项的具体值或选项。
    #[serde(rename = "value")]
    pub value: String,
    /// 用于对设置项进行分类或标记的标签。
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<String>>,
    /// 设置项的详细描述，说明其作用或用途。
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// 指示该设置项是否在前端界面中可用。
    #[serde(rename = "frontendUsable", skip_serializing_if = "Option::is_none")]
    pub frontend_usable: Option<bool>,
    /// 设置项的创建时间。
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// 设置项的最后更新时间。
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
}

impl UserSetting {
    /// 用户配置实体，用于存储用户的个性化设置。
    pub fn new(user_id: i64, code: String, value: String) -> UserSetting {
        UserSetting {
            id: None,
            user_id,
            provider_code: None,
            group_code: None,
            code,
            value,
            tags: None,
            description: None,
            frontend_usable: None,
            create_date: None,
            last_update: None,
        }
    }
}

