/*
 * 用户全部 API 文档
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UserLogins : 用户外部账号
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserLogins {
    /// 唯一标识符
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// 关联的用户ID
    #[serde(rename = "userID", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<i64>,
    /// 第三方平台名称
    #[serde(rename = "platformName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub platform_name: Option<Option<String>>,
    /// 第三方平台
    #[serde(rename = "platform", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub platform: Option<Option<String>>,
    /// 第三方平台唯一标识
    #[serde(rename = "unionID", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub union_id: Option<Option<String>>,
    /// 用户头像
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    /// 扩展数据
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
    /// 启用
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
    /// 创建时间
    #[serde(rename = "createDate", skip_serializing_if = "Option::is_none")]
    pub create_date: Option<String>,
    /// 最后更新时间
    #[serde(rename = "lastUpdate", skip_serializing_if = "Option::is_none")]
    pub last_update: Option<String>,
}

impl UserLogins {
    /// 用户外部账号
    pub fn new() -> UserLogins {
        UserLogins {
            id: None,
            user_id: None,
            platform_name: None,
            platform: None,
            union_id: None,
            avatar: None,
            data: None,
            enable: None,
            create_date: None,
            last_update: None,
        }
    }
}

